### ISSUE TITLE
resin sync copies to incorrect location

### ISSUE THREAD

**Issue by imrehg** [resin-io-modules/resin-sync#35]
Doing a resin sync seem to copy files to the wrong location. Doing one of the host OS test cases, push the [simple-server-node](https://github.com/resin-io-projects/simple-server-node) app, modify `server.js` , sync, and try to see the modifications on the public URL. It does not get modified, as the file appears to be copied to `./. ./server.js` wherever that might be...

I get something like this:

```
$resin sync 166dcf21ebbd5557db3b7742b3039843d82b96b2d5acabd7c4fa9f84d87396
Connecting with: 166dcf21ebbd5557db3b7742b3039843d82b96b2d5acabd7c4fa9f84d87396
Application container stopped.
Synced /usr/src/app on 166dcf2.
Application container started.

resin sync completed successfully!
$resin ssh 166dcf21ebbd5557db3b7742b3039843d82b96b2d5acabd7c4fa9f84d87396
Connecting with: 166dcf21ebbd5557db3b7742b3039843d82b96b2d5acabd7c4fa9f84d87396
root@raspberrypi3-166dcf2:/# find  -name "server.js"
./usr/src/app/server.js
./. ./server.js
root@raspberrypi3-166dcf2:/# 
```

Correct behaviour would be having only one file in `/usr/src/app`.

Using resin cli 4.4.0, testcase bug report is at https://github.com/resin-os/meta-resin/issues/250

Can it be some wrongly escaped directory in the code to actually create a `. .` dir (that is "period-space-period") in `/`?

**Comment by lekkas** [comment]
@imrehg was this on staging on production? The testcase bug report refers to staging. Note that we currently have to use `npm install -g resin-io/resin-cli#features/resin-sync-ssh-improvements` as a client for staging and the normal `npm install -g resin-cli` on production.

**Comment by lekkas** [comment]
@imrehg reping on this ^ - was this ever reproduced or can we close the issue?

**Comment by imrehg** [comment]
Sorry @lekkas, didn't notice this report. The current `5.1.0` seem to sync to the right place, so I think it can be closed.

**Comment by lekkas** [comment]
Cool, no worries 👍
