### ISSUE TITLE
should not save uuid into .resin-sync.yml

### ISSUE THREAD

**Issue by imrehg** [resin-io-modules/resin-sync#44]
When running `resin sync`, it creates the configuration file `.resin-sync.yml`, and:
- saves an `uuid` variable of the devices pushed to
- on next sync it still asks which device to sync to

IMHO should not save the uuid automatically, as `.resin-sync.yml` should be a config that could be checked in to git (no user-specific info automatically), and it's not used either apparently.

**Comment by lekkas** [comment]
@imrehg the `uuid` is used as the default choice on the next sync, so a user can still review which device he is syncing to and even change it if he has > 1 development devices. Using `resin sync [uuid]` is the way to sync to a specific device w/o getting an interactive dialog.

**Comment by lekkas** [comment]
That said, I agree that `uuid` should better not get checked into git, but if we want to keep the default device selection feature we still need to save it somewhere. We could use `resin-settings-storage` and save it under `~/.resin` but it needs some thought on how to properly manage this, because `~/.resin` could start accumulating `stale` default device uuid's from inactive/deleted Resin.io projects.

**Comment by imrehg** [comment]
@lekkas I see, I did not notice that behaviour because the device I synced to was the first one. :P

While I understand the rationale, IMHO this is not needed at all, if want to sync to a specific device, will use `resin sync [uuid]` anyways. This feature is just too hidden, not powerful enough, and have too many side effects.

**Comment by lekkas** [comment]
@imrehg yeah I agree it's easy to miss.

As an occasional `resin sync` user I'm okay with removing it, but I'd first ask feedback from a few `resin sync` power-users as well like @shaunmulligan and @josephroberts , who iirc pitched this feature

**Comment by shaunmulligan** [comment]
I didn't pitch it, it was from Joe's usecase. The rational was that the user could just hit "ENTER" twice, but while working with it, i have found it a bit annoying, because its not two quick "ENTER" hits, there is 3 -5 seconds in between, so you have to wait around :/ I would be up for removing it

**Comment by jbaldwinroberts** [comment]
Fine by me, do we all agree: `resin sync` will sync to the device in the config file if present and if not show you the device selection drop down (saving the selection in the config file) and that `resin sync uuid....` should sync to that device and save the selection in the config file for next time.

**Comment by shaunmulligan** [comment]
yup, i'm happy with that.

**Comment by imrehg** [comment]
thanks for all the feedback, appreciate hearing how people are using these tools! :)

**Comment by pimterry** [comment]
This was resolved (by changing to the behaviour described above) in the linked commit, closing.
